[project]
name = "presentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bigjson>=1.0.9",
    "pandas>=2.3.3",
]
